name: App Workflow

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

permissions:
  contents: read

jobs:
  
  build:
    runs-on: windows-latest
    
    steps:
    - name: Checkout repository
      #run: git clone https://github.com/vaibhavjha100/FNOT.git . 
      uses: actions/checkout@v4
    
    - name: Set up Python
      uses: actions/setup-python@v5
      with: 
        python-version: '3.12.2'
    
    - name: Install poetry
      uses: snok/install-poetry@v1
      with:
        virtualenvs-in-project: true

    - name: Load cached venv
      uses: actions/cache@v4
      id: cached-poetry-dependencies
      with:
        path: /path/to/.venv
        key: venv-${{runner.os}}-${{hashFiles('**/poetry.lock')}}
    
    - name: Install dependencies using poetry
      if: steps.cached-poetry-dependencies.outputs.cache-hit != 'true'
      run:  C:\Users\runneradmin\AppData\Roaming\Python\Scripts\poetry install
